<?php
namespace Database\Seeders;

use App\Http\Controllers\AuthController;
use App\Http\Requests\AuthRequest;
use Illuminate\Database\Seeder;

class UserSeeder extends Seeder {
  public function run(): void {
    $authController = new AuthController();

    $users = [
      [
        'username' => 'john_doe',
        'given_name' => 'John',
        'family_name' => 'Doe',
        'email' => 'john.doe@example.com',
        'password' => 'password1234',
        'bio' => 'Just a regular guy.',
        'location' => 'USA',
        'website' => 'example.com',
        'pronouns' => 'he/him',
      ],
      [
        'username' => 'jane_smith',
        'given_name' => 'Jane',
        'family_name' => 'Smith',
        'email' => 'jane.smith@example.com',
        'password' => 'password1234',
        'bio' => 'Lover of books and coffee.',
        'location' => 'UK',
        'website' => 'booklover.com',
        'pronouns' => 'she/her',
      ],
      [
        'username' => 'alice_wonder',
        'given_name' => 'Alice',
        'family_name' => 'Wonderland',
        'email' => 'alice.wonder@example.com',
        'password' => 'password1234',
        'bio' => 'Curious and adventurous.',
        'location' => 'Wonderland',
        'website' => 'wonder.com',
        'pronouns' => 'she/her',
      ],
      [
        'username' => 'bob_builder',
        'given_name' => 'Bob',
        'family_name' => 'Builder',
        'email' => 'bob.builder@example.com',
        'password' => 'password1234',
        'bio' => 'Can we fix it? Yes, we can!',
        'location' => 'Construction Site',
        'website' => 'buildit.com',
        'pronouns' => 'he/him',
      ],
      [
        'username' => 'charlie_brown',
        'given_name' => 'Charlie',
        'family_name' => 'Brown',
        'email' => 'charlie.brown@example.com',
        'password' => 'password1234',
        'bio' => 'Good grief!',
        'location' => 'Peanuts Town',
        'website' => 'peanuts.com',
        'pronouns' => 'he/him',
      ],
      [
        'username' => 'diana_prince',
        'given_name' => 'Diana',
        'family_name' => 'Prince',
        'email' => 'diana.prince@example.com',
        'password' => 'password1234',
        'bio' => 'Amazonian warrior princess.',
        'location' => 'Themyscira',
        'website' => 'wonderwoman.com',
        'pronouns' => 'she/her',
      ],
      [
        'username' => 'edward_snow',
        'given_name' => 'Edward',
        'family_name' => 'Snow',
        'email' => 'edward.snow@example.com',
        'password' => 'password1234',
        'bio' => 'Loves the winter season.',
        'location' => 'North Pole',
        'website' => 'snowworld.com',
        'pronouns' => 'he/him',
      ],
      [
        'username' => 'fiona_apple',
        'given_name' => 'Fiona',
        'family_name' => 'Apple',
        'email' => 'fiona.apple@example.com',
        'password' => 'password1234',
        'bio' => 'Singer and songwriter.',
        'location' => 'New York',
        'website' => 'fionaapple.com',
        'pronouns' => 'she/her',
      ],
      [
        'username' => 'george_jetson',
        'given_name' => 'George',
        'family_name' => 'Jetson',
        'email' => 'george.jetson@example.com',
        'password' => 'password1234',
        'bio' => 'Living in the future.',
        'location' => 'Orbit City',
        'website' => 'jetsons.com',
        'pronouns' => 'he/him',
      ],
      [
        'username' => 'hank_hill',
        'given_name' => 'Hank',
        'family_name' => 'Hill',
        'email' => 'hank.hill@example.com',
        'password' => 'password1234',
        'bio' => 'Propane and propane accessories.',
        'location' => 'Arlen, Texas',
        'website' => 'stricklandpropane.com',
        'pronouns' => 'he/him',
      ],
      [
        'username' => 'iris_west',
        'given_name' => 'Iris',
        'family_name' => 'West',
        'email' => 'iris.west@example.com',
        'password' => 'password1234',
        'bio' => 'Journalist and speedster spouse.',
        'location' => 'Central City',
        'website' => 'centralcitynews.com',
        'pronouns' => 'she/her',
      ],
      [
        'username' => 'jack_sparrow',
        'given_name' => 'Jack',
        'family_name' => 'Sparrow',
        'email' => 'jack.sparrow@example.com',
        'password' => 'password1234',
        'bio' => 'Captain of the Black Pearl.',
        'location' => 'The Caribbean',
        'website' => 'piratebay.com',
        'pronouns' => 'he/him',
      ],
      [
        'username' => 'karen_page',
        'given_name' => 'Karen',
        'family_name' => 'Page',
        'email' => 'karen.page@example.com',
        'password' => 'password1234',
        'bio' => 'Journalist at the Daily Bugle.',
        'location' => 'New York',
        'website' => 'dailybugle.com',
        'pronouns' => 'she/her',
      ],
      [
        'username' => 'leo_messi',
        'given_name' => 'Lionel',
        'family_name' => 'Messi',
        'email' => 'leo.messi@example.com',
        'password' => 'password1234',
        'bio' => 'Professional footballer.',
        'location' => 'Barcelona',
        'website' => 'fcbarcelona.com',
        'pronouns' => 'he/him',
      ],
      [
        'username' => 'mary_jane',
        'given_name' => 'Mary',
        'family_name' => 'Jane',
        'email' => 'mary.jane@example.com',
        'password' => 'password1234',
        'bio' => 'Actress and model.',
        'location' => 'New York',
        'website' => 'mjmodel.com',
        'pronouns' => 'she/her',
      ],
      [
        'username' => 'ned_stark',
        'given_name' => 'Eddard',
        'family_name' => 'Stark',
        'email' => 'ned.stark@example.com',
        'password' => 'password1234',
        'bio' => 'Warden of the North.',
        'location' => 'Winterfell',
        'website' => 'winteriscoming.com',
        'pronouns' => 'he/him',
      ],
      [
        'username' => 'oliver_queen',
        'given_name' => 'Oliver',
        'family_name' => 'Queen',
        'email' => 'oliver.queen@example.com',
        'password' => 'password1234',
        'bio' => 'Billionaire vigilante.',
        'location' => 'Star City',
        'website' => 'qcorp.com',
        'pronouns' => 'he/him',
      ],
      [
        'username' => 'peter_parker',
        'given_name' => 'Peter',
        'family_name' => 'Parker',
        'email' => 'peter.parker@example.com',
        'password' => 'password1234',
        'bio' => 'Friendly neighborhood Spider-Man.',
        'location' => 'New York',
        'website' => 'spiderman.com',
        'pronouns' => 'he/him',
      ],
      [
        'username' => 'quinn_harley',
        'given_name' => 'Harleen',
        'family_name' => 'Quinzel',
        'email' => 'quinn.harley@example.com',
        'password' => 'password1234',
        'bio' => 'Psychiatrist turned supervillain.',
        'location' => 'Gotham City',
        'website' => 'arkhamasylum.com',
        'pronouns' => 'she/her',
      ],
      [
        'username' => 'rick_grimes',
        'given_name' => 'Rick',
        'family_name' => 'Grimes',
        'email' => 'rick.grimes@example.com',
        'password' => 'password1234',
        'bio' => 'Sheriff and survivor.',
        'location' => 'Alexandria',
        'website' => 'twd.com',
        'pronouns' => 'he/him',
      ],
      [
        'username' => 'sarah_connor',
        'given_name' => 'Sarah',
        'family_name' => 'Connor',
        'email' => 'sarah.connor@example.com',
        'password' => 'password1234',
        'bio' => 'Fighting the machines.',
        'location' => 'Los Angeles',
        'website' => 'terminator.com',
        'pronouns' => 'she/her',
      ],
      [
        'username' => 'tony_stark',
        'given_name' => 'Tony',
        'family_name' => 'Stark',
        'email' => 'tony.stark@example.com',
        'password' => 'password1234',
        'bio' => 'Genius, billionaire, playboy, philanthropist.',
        'location' => 'New York',
        'website' => 'starkindustries.com',
        'pronouns' => 'he/him',
      ],
      [
        'username' => 'ulysses_grant',
        'given_name' => 'Ulysses',
        'family_name' => 'Grant',
        'email' => 'ulysses.grant@example.com',
        'password' => 'password1234',
        'bio' => '18th President of the United States.',
        'location' => 'Washington, D.C.',
        'website' => 'whitehouse.gov',
        'pronouns' => 'he/him',
      ],
      [
        'username' => 'victor_frankenstein',
        'given_name' => 'Victor',
        'family_name' => 'Frankenstein',
        'email' => 'victor.frankenstein@example.com',
        'password' => 'password1234',
        'bio' => 'Mad scientist.',
        'location' => 'Geneva',
        'website' => 'frankenstein.com',
        'pronouns' => 'he/him',
      ],
      [
        'username' => 'wanda_maximoff',
        'given_name' => 'Wanda',
        'family_name' => 'Maximoff',
        'email' => 'wanda.maximoff@example.com',
        'password' => 'password1234',
        'bio' => 'The Scarlet Witch.',
        'location' => 'Sokovia',
        'website' => 'avengers.com',
        'pronouns' => 'she/her',
      ],
      [
        'username' => 'xavier_charles',
        'given_name' => 'Charles',
        'family_name' => 'Xavier',
        'email' => 'charles.xavier@example.com',
        'password' => 'password1234',
        'bio' => 'Professor X.',
        'location' => 'Westchester',
        'website' => 'xmen.com',
        'pronouns' => 'he/him',
      ],
      [
        'username' => 'yara_flor',
        'given_name' => 'Yara',
        'family_name' => 'Flor',
        'email' => 'yara.flor@example.com',
        'password' => 'password1234',
        'bio' => 'The new Wonder Girl.',
        'location' => 'Brazil',
        'website' => 'amazons.com',
        'pronouns' => 'she/her',
      ],
      [
        'username' => 'zelda_fitzgerald',
        'given_name' => 'Zelda',
        'family_name' => 'Fitzgerald',
        'email' => 'zelda.fitzgerald@example.com',
        'password' => 'password1234',
        'bio' => 'American socialite and novelist.',
        'location' => 'Montgomery, Alabama',
        'website' => 'zeldafitzgerald.com',
        'pronouns' => 'she/her',
      ],
      [
        'username' => 'arthur_dent',
        'given_name' => 'Arthur',
        'family_name' => 'Dent',
        'email' => 'arthur.dent@example.com',
        'password' => 'password1234',
        'bio' => 'Hitchhiker in the galaxy.',
        'location' => 'Earth',
        'website' => 'dontpanic.com',
        'pronouns' => 'he/him',
      ],
      [
        'username' => 'beatrice_prior',
        'given_name' => 'Beatrice',
        'family_name' => 'Prior',
        'email' => 'beatrice.prior@example.com',
        'password' => 'password1234',
        'bio' => 'Divergent and fearless.',
        'location' => 'Chicago',
        'website' => 'divergent.com',
        'pronouns' => 'she/her',
      ],
      [
        'username' => 'frodo_baggins',
        'given_name' => 'Frodo',
        'family_name' => 'Baggins',
        'email' => 'frodo.baggins@example.com',
        'password' => 'password1234',
        'bio' => 'Ring-bearer.',
        'location' => 'The Shire',
        'website' => 'middleearth.com',
        'pronouns' => 'he/him',
      ],
      [
        'username' => 'hermione_granger',
        'given_name' => 'Hermione',
        'family_name' => 'Granger',
        'email' => 'hermione.granger@example.com',
        'password' => 'password1234',
        'bio' => 'Brightest witch of her age.',
        'location' => 'Hogwarts',
        'website' => 'hogwarts.com',
        'pronouns' => 'she/her',
      ],
    ];

    foreach ($users as $userData) {
      $request = AuthRequest::create('signup', 'POST', $userData);
      $authController->signup($request);
    }
  }
}
