name: plotscore laravel backend deployment

on:
  push:
    branches: ["main"]

jobs:
  backend:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: set up php
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: install composer dependencies
      run: |
        cd desktop/backend
        composer install

    - name: create .env file from template
      run: |
        cd desktop/backend
        cp .env.example .env
        sed -i 's/DB_HOST=.*/DB_HOST=${{ secrets.DB_HOST }}/' .env
        sed -i 's/DB_PORT=.*/DB_PORT=${{ secrets.DB_PORT }}/' .env
        sed -i 's/DB_DATABASE=.*/DB_DATABASE=${{ secrets.DB_DATABASE }}/' .env
        sed -i 's/DB_USERNAME=.*/DB_USERNAME=${{ secrets.DB_USERNAME }}/' .env
        sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=${{ secrets.DB_PASSWORD }}/' .env
        sed -i 's/ADMIN_SECRET_KEY=.*/ADMIN_SECRET_KEY=${{ secrets.ADMIN_SECRET_KEY }}/' .env

    - name: serve the application
      run: |
        cd desktop/backend
        nohup php artisan serve --host=0.0.0.0 --port=8000 &
