name: plotscore next.js app deployment

on:
  push:
    branches: ["main"]

jobs:
  deploy-nextjs-app:
    runs-on: self-hosted
    # strategy:
    #   matrix:
    #     node-version: [22.x]

    steps:
    - uses: actions/checkout@v4

    - name: deploy next.js app
      run: |
        cd desktop/frontend
        npm ci
        npm run build
        npm run start
        cd ../..
        pm2 start ecosystem.config.js --only nextjs-app

    # - name: build project
    #   run: |
    #     cd desktop/frontend
    #     npm run build

    # - name: start app
    #   run: |
    #     pm2 start ecosystem.config.js --only nextjs-app
