name: plotscore next.js app deployment

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        cd desktop/frontend
        npm ci
    - name: build project
      run: |
        pm2 start "npm run build && npm run start" --name=nextjs-app
