name: plotscore next.js app deployment

on:
  push:
    branches: ["main"]

jobs:
  deploy-nextjs-app:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: deploy next.js app
      run: |
        cd desktop/frontend
        npm ci
        npm run build
        cd ../..
        pm2 start ecosystem.config.js --only nextjs-app

  deploy-laravel-app:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: set up php
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: deploy laravel app
      run: |
        cd desktop/backend
        composer install

        cp .env.example .env
        sed -i 's/DB_HOST=.*/DB_HOST=${{ secrets.DB_HOST }}/' .env
        sed -i 's/DB_PORT=.*/DB_PORT=${{ secrets.DB_PORT }}/' .env
        sed -i 's/DB_DATABASE=.*/DB_DATABASE=${{ secrets.DB_DATABASE }}/' .env
        sed -i 's/DB_USERNAME=.*/DB_USERNAME=${{ secrets.DB_USERNAME }}/' .env
        sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=${{ secrets.DB_PASSWORD }}/' .env
        sed -i 's/ADMIN_SECRET_KEY=.*/ADMIN_SECRET_KEY=${{ secrets.ADMIN_SECRET_KEY }}/' .env

        php artisan key:generate
        php artisan migrate:refresh --seed
        php artisan serve --port=8000
