name: deploy plotscore project

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: deploy next.js app
      run: |
        cd desktop/frontend
        npm ci
        npm run build

    - name: set up php
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer

    - name: deploy laravel app
      run: |
        cd desktop/backend
        composer install

        cp .env.example .env
        sed -i "s|APP_ENV=.*|APP_ENV=production|" .env
        sed -i "s|APP_DEBUG=.*|APP_DEBUG=false|" .env
        sed -i "s|DB_HOST=.*|DB_HOST=${{ secrets.DB_HOST }}|" .env
        sed -i "s|DB_PORT=.*|DB_PORT=${{ secrets.DB_PORT }}|" .env
        sed -i "s|DB_DATABASE=.*|DB_DATABASE=${{ secrets.DB_DATABASE }}|" .env
        sed -i "s|DB_USERNAME=.*|DB_USERNAME=${{ secrets.DB_USERNAME }}|" .env
        sed -i "s|DB_PASSWORD=.*|DB_PASSWORD=${{ secrets.DB_PASSWORD }}|" .env
        sed -i "s|ADMIN_SECRET_KEY=.*|ADMIN_SECRET_KEY=${{ secrets.ADMIN_SECRET_KEY }}|" .env

        php artisan key:generate --force

        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
        php artisan migrate --force
        php artisan storage:link

    - name: start next.js app in production mode
      run: |
        pm2 stop all || true
        cd desktop/frontend
        NODE_ENV=production pm2 start npm --name "nextjs" -- start

    - name: restart apache
      run: sudo systemctl restart apache2
