name: deploy frontend

on:
  push:
    paths:
      - 'desktop/frontend/**'
    branches: ["main"]

jobs:
  build:
    runs-on: [self-hosted, frontend-runner]
    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        cd desktop/frontend
        npm ci
    - name: build and deploy
      run: |
        cd desktop/frontend
        npm run build
        pm2 restart plotscore
